### ISSUE TITLE
Unhandled command CC_GET_PRO with swiss-gc r1336 (latest)

### ISSUE THREAD

**Issue by tlrmcknz** [GoobyCorp/fspd#3]
Swiss r1336 stays on "Setting up device" and python console has repeating output of:

FSPCommand.CC_GET_PRO
Key: 32794
Seq: 36040
Pos: 0
b'swiss/patches\n\x00'
FSPCommand.CC_GET_PRO
Key: 32794
Seq: 36041
Pos: 0
b'swiss/patches\n\x00'

etc...

**Comment by GoobyCorp** [comment]
I'll try and implement this tonight, it appears to be a new feature from a quick glance.

On July 14, 2022 3:12:21 PM EDT, tlrmcknz ***@***.***> wrote:
>Swiss r1336 stays on "Setting up device" and python console has repeating output of:
>
>FSPCommand.CC_GET_PRO
>Key: 32794
>Seq: 36040
>Pos: 0
>b'swiss/patches\n\x00'
>FSPCommand.CC_GET_PRO
>Key: 32794
>Seq: 36041
>Pos: 0
>b'swiss/patches\n\x00'
>
>etc...
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/GoobyCorp/fspd/issues/3
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by GoobyCorp** [comment]
I've tested the latest commit with Metroid Prime, Paper Mario The Thousand Year Door, and Zelda Windwaker. Hopefully this solves your issues, reopen if it doesn't.
